[package]

name = "maud_macros"
# When releasing a new version, please update html_root_url in src/lib.rs
version = "0.16.3"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

license = "MIT/Apache-2.0"
documentation = "https://docs.rs/maud_macros/"
homepage = "https://maud.lambda.xyz/"
repository = "https://github.com/lfairy/maud"
description = "Compile-time HTML templates."

[dependencies]
if_chain = "0.1"
literalext = { git = "https://github.com/mystor/literalext.git", default-features = false, features = ["proc-macro"] }

[lib]
name = "maud_macros"
proc-macro = true

[badges]
travis-ci = { repository = "lfairy/maud" }
